### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by achinrocker** [dhruvagarwal/geekometer#5]
is this some problem of my browser settings or some problem of the extension ->

basically i lose out my contents ,,ie,, what ever is marked or saved gets automatically cleared up ,,,the next day when i open up the browser.. and also some pages dont get marked ...
i have been using chrome ...

**Comment by dhruvagarwal** [comment]
Hey

The contents are not intended to be lost unless a browser history and data clean up is issued.
I think there is some other problem going on with your browser .
This extension is right now limited to only geeksforgeeks.org, other pages are geeksquiz ones . I am just gonna update the new version with this update, so it will be resolved soon.

Happy coding !
