### ISSUE TITLE
Don't need to open Pages in different tabs.

### ISSUE THREAD

**Issue by vicky002** [dhruvagarwal/geekometer#7]
Currently when I click on the page link, it opens in a new tab. It will be good if we can open in the same tab.

**Comment by dhruvagarwal** [comment]
yes, good point. it should be rather a configurable option(or rather toggle). Earlier i added it on request such that the current context doesn't change

**Comment by vicky002** [comment]
yess, so add label of enhancement here.. we should work on this. Will make the changes in the next update. (y)

**Comment by KARTIK01** [comment]
comment line no 58 in main.js and 125 in funcs.js
```javascript
// a_s[j].setAttribute("target","_blank");
```

**Comment by dhruvagarwal** [comment]
Fixed
